Fix uploading s3 url issues in cogames upload (#4697)
Currently in main I if try to upload policies which are s3 uri's I get
the following error:
```
➜  metta git:(main) uv run cogames upload -p s3://softmax-public/policies/subho.machina_1_cloner.longerrun.AgSA.epoch1/subho.machina_1_cloner.longerrun.AgSA.epoch1:v570.zip -n subho.cortexmain.kickstarted
      Built mettagrid @ file:///Users/subho/Documents/projects/metta/packages/mettagrid
Uninstalled 1 package in 0.57ms
Installed 1 package in 1ms
Error: Path must be relative: 
/private/tmp/mettagrid-policy-cache/7507eb6f91d768cb81d718aa0796fce02e03f8582a79a7513ce
32d79ab77a2e5.d/weights.safetensors
```